---

- name: Configuration data
  become: "{{ ansible_user_id }}"
  ansible.builtin.command:
    cmd: |
      echo "
      env                         ==>  {{ "Env" }}
      node.name                   ==>  {{ "es_node_name" }}
      "
  delegate_to: localhost
  register: config_out
  changed_when: false

- name: Print config
  ansible.builtin.debug:
    var: config_out.stdout_lines
  when: config_out is defined

- name: Users elasticsearch
  ansible.builtin.import_tasks: users.yml

- name: Configure elasticsearch
  ansible.builtin.import_tasks: configure.yml

- name: Install docker elasticsearch
  ansible.builtin.import_tasks: install.yml
