---
- name: Restart elasticsearch
  ansible.builtin.service:
    name: Elasticsearch
    state: restarted
    enabled: true

- name: Reload elasticsearch
  ansible.builtin.systemd:
    name: Elasticsearch
    state: reloaded

- name: Start elasticsearch
  ansible.builtin.systemd:
    name: Elasticsearch
    state: started
