---
- name: restart elasticsearch
  service:
    name: elasticsearch
    state: restarted
    enabled: true

- name: reload elasticsearch
  systemd:
    name: elasticsearch
    state: reloaded

- name: start elasticsearch
  systemd:
    name: elasticsearch
    state: started
