#!/usr/bin/env bash

docker pull docker.elastic.co/elasticsearch/elasticsearch:"{{ es_version }}"

docker rm -f -v elasticsearch || :

docker run -u  root  --rm --name=elasticsearch \
         -p {{ es_port }}:{{ es_port }} -p{{ es_publish_port }}:{{ es_publish_port }} \
         --ulimit nproc=65535 --ulimit memlock=-1:-1 --ulimit nofile=65535:65535  \
         --log-driver json-file --log-opt max-size=500k --log-opt max-file=50 \
         -e ES_JAVA_OPTS="-Xms1g -Xmx1g" \
         -e "discovery.type=single-node" \
         -v {{ es_log_dir }}:{{ es_log_dir }} \
         -v {{ es_tmp_dir }}:/tmp/elasticsearch \
         -v {{ es_config_dir }}/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml \
         -v {{ es_config_dir }}/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties \
         -v {{ es_data_dir }}:/usr/share/elasticsearch/data \
         docker.elastic.co/elasticsearch/elasticsearch:{{ es_version }}